### ISSUE TITLE
Get "warning: can only update a mounted component" after going to admin screen

### ISSUE THREAD

**Issue by rjmcdougall** [rjmcdougall/BB#51] opened 2018-05-19 17:28 UTC
![image](https://user-images.githubusercontent.com/79043/40271236-51dd10f4-5b4f-11e8-98bb-8709849f2a3b.png)

**Comment by danielkeithw** [comment] 2018-06-03 19:05
Cannot reproduce. likely fixed by previous.

**Closed** 2018-06-03 19:06 UTC
Labels: BB Mobile App
